Make XAPIAN_NONNULL a no-op for GCC 4.8
It seems to give false positive warnings:

In file included from ./common/submatch.h:24:0,
                 from matcher/multimatch.h:27,
                 from matcher/multimatch.cc:28:
./include/xapian/intrusive_ptr.h: In instantiation of ‘Xapian::Internal::intrusive_ptr_nonnull<T>& Xapian::Internal::intrusive_ptr_nonnull<T>::operator=(T*) [with T = Xapian::MSet::Internal]’:
matcher/multimatch.cc:318:16:   required from here
./include/xapian/intrusive_ptr.h:224:9: error: null argument where non-null required (argument 1) [-Werror=nonnull]
         this_type(rhs).swap(*this);
         ^