Fix Database::locked() on single-file glass db
Previously this failed with:

DatabaseLockError: Unable to get write lock on /flintlock: Testing lock

Now it returns false (such databases can't be opened as a
WritableDatabase so there can't be a write lock).

(cherry picked from commit 88c27c9d914b40edbca1b8c21c582b0ba66cfc25)