Don't use extern "C" for functions which can throw
MSVC doesn't like this and gives this warning (rather misleadingly as
nothing in the list was actually specified):

languages/utilities.cc(31): error C2220: the following warning is treated as an error
languages/utilities.cc(31): warning C4297: 'create_s': function assumed not to throw an exception but does
languages/utilities.cc(31): note: __declspec(nothrow), throw(), noexcept(true), or noexcept was specified on the function